inoreabbrev Tdate <C-R>=strftime("%d-%b-%Y")<CR>
inoreabbrev Gdate <C-R>=strftime("%FT%T")<CR>
inoreabbrev ryme rhyme
inoreabbrev undering understanding
inoreabbrev understaning understanding
inoreabbrev graphql GraphQL
iabbrev dont don't
inoreabbrev mdl []()
iabbrev syntac syntax
iabbrev zfz fzf
