inoreabbrev Fdate <C-R>=strftime("%d-%b-%Y")<CR>
inoreabbrev Gdate <C-R>=strftime("%FT%T")<CR>
inoreabbrev Tdate <C-R>=strftime("%a %d, %b %Y")<CR>
inoreabbrev ryme rhyme
inoreabbrev undering understanding
inoreabbrev understaning understanding
inoreabbrev graphql GraphQL
iabbrev dont don't
inoreabbrev mdl []()
iabbrev syntac syntax
iabbrev zfz fzf
iabbrev lpdb lilypad-db
iabbrev T$ 
iabbrev TT$ 
iabbrev B$ ﬘
iabbrev :-) 
iabbrev :D 
iabbrev grm Guilherme
iabbrev chk ✔
iabbrev pi π
