# custom aliases
alias -s js=nvim
alias -s zsh=nvim
alias -s txt=nvim
alias -s md=nvim
alias -s MD=nvim
alias yp='pwd|pbcopy'
alias vt='nvim +terminal'
alias vd='nvim -d'
alias vdro='nvim -d -R'
alias triage='nvim ~/notes/rust/triage-template'
alias cpwd='pwd|pbcopy'
alias ppwd='pbpaste'
alias v='nvim'
alias vsl='nvim -S ~/vim-sessions/latest.ses'
alias gCal='cd ~/oss/gCal'
alias gijs='git init && echo "node_modules" >> .gitignore'
alias ng='npm init -y && git init && echo "node_modules" >> .gitignore'
alias hack='history -75 | ack'
alias dots='zsh ~/dotfiles/index.txt'
alias cpnotes='cp -R  ~/notes/ ~/Dropbox/notes'
alias nij='node inspect node_modules/.bin/jest --runInBand'
alias jlc='jest --config=jest.local.js'
alias ghil='gh issue list'
alias exat='exa -aTI "node_modules|.git|coverage"'
alias exal='exa -allI "node_modules|.git|coverage"'
alias exaf='exa -allFI "node_modules|.git|coverage"'
alias vc='nvim -O ~/.config/nvim/init.vim ~/.vimrc'
alias nvc='nvim ~/.config/nvim/init.vim'
alias gt='git difftool --no-prompt'
alias tl1='tree -L 1'
alias cov='open coverage/index.html'
alias note='nvim ~/notes/'
alias arec='asciinema rec'
